version: '3.8'


services:
  db:
    image: postgres:13
    env_file:
      - .env  # Используем переменные из .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:2248633q@db:5432/diary
      DJANGO_SETTINGS_MODULE: diary_platform.settings.local
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  static_volume:







